apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
    namespace 'com.lukekorth.screennotifications'
    compileSdkVersion 34

    defaultConfig {
        applicationId 'com.lukekorth.screennotifications'
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 22
        versionName "0.14.2"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }
}

dependencies {
    implementation 'com.android.support:appcompat-v7:25.3.1'
    implementation 'com.github.lkorth:MailableLog:0.1.6'
    implementation 'com.github.PomepuyN:DiscreetAppRate:d9e007907d'
}
